### ISSUE TITLE
[CIS] content conflicts with data 

### ISSUE THREAD

**Issue by VidyasagarMSC** [terraform-ibm-modules/terraform-ibm-cis#350]
### Affected modules

* CIS 

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

```
Terraform v1.4.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/ibm-cloud/ibm v1.56.0
+ provider registry.terraform.io/logdna/logdna v1.14.2
```

### Expected behavior

As a user, I should either content or data or both. But, looks like both content and data are required.

### Actual behavior

```
│ Error: Conflicting configuration arguments
│
│   with module.cis_domain.ibm_cis_dns_record.dns_rescords["test-exmple.loc/LOC"],
│   on .terraform/modules/cis_domain/modules/domain/main.tf line 35, in resource "ibm_cis_dns_record" "dns_rescords":
│   35:   content   = lookup(each.value, "content", null)
│
│ "content": conflicts with data
╵
╷
│ Error: Conflicting configuration arguments
│
│   with module.cis_domain.ibm_cis_dns_record.dns_rescords["test-exmple.loc/LOC"],
│   on .terraform/modules/cis_domain/modules/domain/main.tf line 36, in resource "ibm_cis_dns_record" "dns_rescords":
│   36:   data      = lookup(each.value, "data", null)
│
│ "data": conflicts with content
```

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by maheshwarishikha** [comment]
@VidyasagarMSC thanks for reaching out.
We should provide either content or data, not both. Will fix it in the code to avoid confusion and update you soon.
 Thanks

**Comment by iamar7** [comment]
PR Merged, Closing the issue.
